- title: Subscriptions
  feedSources:
    - apiType: Invidious
      endpoint: auth_feed

- title: Trending
  feedSources:
    - apiType: Invidious
      endpoint: trending

- title: Trending - Music
  feedSources:
    - apiType: Invidious
      endpoint: trending
      queryParams:
        type: Music

- title: Trending - Gaming
  feedSources:
    - apiType: Invidious
      endpoint: trending
      queryParams:
        type: Gaming

- title: Trending - Movies
  feedSources:
    - apiType: Invidious
      endpoint: trending
      queryParams:
        type: Movies

- title: Popular
  feedSources:
    - apiType: Invidious
      endpoint: popular

- title: Funny
  feedSources:
    - apiType: Invidious
      endpoint: search
      queryParams:
        q: Funny
        sort_by: upload_date

- title: News
  feedSources:
    - apiType: Invidious
      endpoint: search
      queryParams:
        q: News
        sort_by: upload_date

- title: Playlists
  feedSources:
    - apiType: Invidious
      endpoint: auth_playlists
