- title: Continue watching
  feedSources:
    - id: local_continue_watching
      title: Continue watching
      apiType: Local
      endpoint: continue_watching

- title: Subscriptions
  feedSources:
    - id: inv_auth_feed
      title: Subscriptions
      apiType: Invidious
      endpoint: auth_feed

- title: Trending
  feedSources:
    - id: inv_trending
      title: Trending
      apiType: Invidious
      endpoint: trending

- title: Trending - Music
  feedSources:
    - id: inv_trending_music
      title: Trending - Music
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Music

- title: Trending - Gaming
  feedSources:
    - id: inv_trending_gaming
      title: Trending - Gaming
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Gaming

- title: Trending - Movies
  feedSources:
    - id: inv_trending_movies
      title: Trending - Movies
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Movies

- title: Popular
  feedSources:
    - id: inv_popular
      title: Popular
      apiType: Invidious
      endpoint: popular

- title: Funny
  feedSources:
    - id: inv_search_funny
      title: Search - Funny
      apiType: Invidious
      endpoint: search
      queryParams:
        q: Funny
        sort_by: upload_date

- title: News
  feedSources:
    - id: inv_search_news
      title: Search - News
      apiType: Invidious
      endpoint: search
      queryParams:
        q: News
        sort_by: upload_date

- title: Playlists
  feedSources:
    - id: inv_auth_playlists
      title: Playlists
      apiType: Invidious
      endpoint: auth_playlists

- title: Watch history
  feedSources:
    - id: local_watch_history
      title: Watch history
      apiType: Local
      endpoint: watch_history
