# TODO:P0
# - Add router that returns videos for continue watching, including watch date and progress (returns them sorted and paginated)
#   - It would return small page size (like 5) but includes video info?
# - Add a node for storing videos in memory, and write to registry, with a limit of 100 videos
#   - Should contain a subnode for each video, so that renderers can observe changes
# - Add settings
#   - Enable/disable continue watching
#   - Max days to keep videos (videos expire based on last watch date)
#   - Video count (capped at 100)
#   - A button to clear all videos
# - Videos with about 95% progress (capped at 1 minute) should be considered watched
# - Add progress bar to video cell (this means "progress" is going to be a field in VideoContentNode)
#   - Also add it to PlaylistViewCell
# - Add support for web app
#   - Rendering the new feed
#   - Casting / Queuing the video should continue from the last watch position
- title: Continue watching
  feedSources:
    - id: local_continue_watching
      title: Continue watching
      apiType: Local
      endpoint: continue_watching

- title: Subscriptions
  feedSources:
    - id: inv_auth_feed
      title: Subscriptions
      apiType: Invidious
      endpoint: auth_feed

- title: Trending
  feedSources:
    - id: inv_trending
      title: Trending
      apiType: Invidious
      endpoint: trending

- title: Trending - Music
  feedSources:
    - id: inv_trending_music
      title: Trending - Music
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Music

- title: Trending - Gaming
  feedSources:
    - id: inv_trending_gaming
      title: Trending - Gaming
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Gaming

- title: Trending - Movies
  feedSources:
    - id: inv_trending_movies
      title: Trending - Movies
      apiType: Invidious
      endpoint: trending
      queryParams:
        type: Movies

- title: Popular
  feedSources:
    - id: inv_popular
      title: Popular
      apiType: Invidious
      endpoint: popular

- title: Funny
  feedSources:
    - id: inv_search_funny
      title: Search - Funny
      apiType: Invidious
      endpoint: search
      queryParams:
        q: Funny
        sort_by: upload_date

- title: News
  feedSources:
    - id: inv_search_news
      title: Search - News
      apiType: Invidious
      endpoint: search
      queryParams:
        q: News
        sort_by: upload_date

- title: Playlists
  feedSources:
    - id: inv_auth_playlists
      title: Playlists
      apiType: Invidious
      endpoint: auth_playlists

- title: Watch history
  feedSources:
    - id: inv_auth_history
      title: Watch history
      apiType: Invidious
      endpoint: watch_history
