continue_watching:
  title: Continue watching
  url: /api/continue-watching
  paginationType: Pages

watch_history:
  title: Watch history
  url: /api/watch-history
  authenticated: true
  paginationType: Pages
