name: Release

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Playlet
        run: npm run build:release:ci

      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Download the Static Channel Analysis CLI
        run: |
          curl -sSL "https://devtools.web.roku.com/static-channel-analysis/sca-cmd.zip" -o sca-cmd.zip
          unzip sca-cmd.zip

      - name: Run Analysis on Playlet Lib
        # Note: we don't set the exit code to on error, because sca treats the lib
        # as a standalone app, and logs all sorts of errors that are not relevant to
        # a Component Library.
        # This run is simply to check if there's any interesting output comes up.
        run: ./sca-cmd/bin/sca-cmd ./playlet/src/lib/playlet-lib.zip

      - name: Run Analysis on Playlet App
        run: ./sca-cmd/bin/sca-cmd ./release/playlet.zip --exit error

      - name: Delete unstable release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: unstable
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Extract changelog
        run: |
          latest_release=$(awk 'BEGIN { RS="## \\[" } NR==2 { print "## ["$0 }' CHANGELOG.md)
          echo -e "\n$latest_release" >> docs/unstable-changelog.md

      - name: Create unstable release
        run: gh release create unstable ./release/playlet.zip ./playlet/src/lib/playlet-lib.zip --notes-file docs/unstable-changelog.md --prerelease --title unstable
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
