name: Release

on:
  push:
    branches: [ "main" ]

jobs:    
  release: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Playlet
        run: npm run build:release:ci
        
      - name: Create unstable release if needed
        run: gh release view unstable || gh release create unstable --prerelease

      - name: Update unstable release
        run: gh release edit unstable --notes "This is an automated release." --prerelease --title unstable

      - name: Replace release assets
        run: gh release upload unstable ./release/playlet.zip ./playlet/src/lib/playlet-lib.zip --clobber
